### ISSUE TITLE
Adding a Network to a Coin

### ISSUE THREAD

**Issue by amlewis4** [libovness/coindexter#67]
I tried to the Ethereum network to the Iconomi coin, but it is not working.

**Comment by libovness** [comment]
You tried adding a network to a network?

**Comment by amlewis4** [comment]
Ah, nevermind. I was doing something wrong.

**Comment by libovness** [comment]
doing something wrong or the UI misled you?

**Comment by libovness** [comment]
I am more formally requiring that a coin must belong to a network, which should fix this issue. 

If this website stands for anything it's that coins are only as interesting as the network they belong to, and so I'm going to enforce that.

**Comment by amlewis4** [comment]
Good idea!

Ari

On Sun, May 21, 2017 at 6:13 PM, Jonathan Libov <notifications@github.com>
wrote:

> I am more formally requiring that a coin must belong to a network, which
> should fix this issue.
>
> If this website stands for anything it's that coins are only as
> interesting as the network they belong to, and so I'm going to enforce that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/6792f77321aec44a06cf275e5946f69ec7c9eded?url=https%3A%2F%2Fgithub.com%2Flibovness%2Fcoindexter%2Fissues%2F67%23issuecomment-302966931&userId=94662&signature=056e78f7e436ab61>,
> or mute the thread
> <https://mailtrack.io/trace/link/09faaa5fcac09c505dc21480d4291b7993b0ad61?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEfCxRcjt3UqA4sijBhoEhBUXuw0j5tGks5r8LcMgaJpZM4Nb8N5&userId=94662&signature=231e2f3584443857>
> .
>



-- 

Subscribe to my weekly newsletter
<https://mailtrack.io/trace/link/d299d8e3bced4cb37b663d0b4a2334685fa09674?url=https%3A%2F%2Fwww.getrevue.co%2Fprofile%2Famlewis4&userId=94662&signature=56807d0a069c8a8f>
about investing in cryptocurrency.

**Comment by libovness** [comment]
@amlewis4 happy to hear that. I hope that philosophy makes the app stand out during the coin mania.

**Comment by libovness** [comment]
*this coin mania
